### ISSUE TITLE
Enable (some) animations even if the user prefers reduced motion

### ISSUE THREAD

**Issue by mtsknn** [formkit/auto-animate#21]
Currently all animations are disabled if the user prefers reduced motion: https://github.com/formkit/auto-animate/blob/1.0.0-beta.1/src/index.ts#L563-L564

```js
const mediaQuery = window.matchMedia("(prefers-reduced-motion: reduce)")
if (mediaQuery.matches) return
```

However, ["No motion isn't always prefers-reduced-motion."](https://css-tricks.com/nuking-motion-with-prefers-reduced-motion/) Disabling all animations can actually be bad for accessibility. Check the ["Reduced motion vs. nuked motion" section](https://css-tricks.com/nuking-motion-with-prefers-reduced-motion/#aa-reduced-motion-vs-nuked-motion) for a good example.

Two ideas:

1. Adjust the animations/transitions to be less distracting when the user prefers reduced motion.
2. Enable all animations by default, and allow disabling individual animations by setting an option like `disableIfUserPrefersReducedMotion` (what a mouthful) to `true`.

If the 1st one is implemented, not sure if there's a need for the 2nd one.

**Comment by mtsknn** [comment]
A general `enabled` or `disabled` option (#27) could work as well and would leave the decision to disable potentially distracting animations to the library users.

```jsx
const prefersReducedMotion = usePrefersReducedMotion()
const [ref] = useAutoAnimate({ disabled: prefersReducedMotion })
```

**Comment by joaomanke** [comment]
+1 to this!

In my use case, I work in a company that sets reduced motion as default for all computers, however in some cases we need to enforce animation, to make list transitions clearer.

I can submit a PR if necessary.

The package is currently unusable because of this, but I would love to switch all my manual animations with this godsend of a library.

**Comment by aderchox** [comment]
Yeah I'd like to request this too, and I want like to recommend adding a button on the main website demo/#examples/showcase section to enable animations even if reduced mode is enabled. I don't like to change my whole system settings in order to only check the demos, and even worse, the whole time I'm developing using this library... I'm personally an animations-off guy on my own system, but I am "required" to use animations in some projects, so... .
Thank you.

**Comment by justin-schroeder** [comment]
This is available: https://auto-animate.formkit.com/#configuration
