### ISSUE TITLE
Option to disable animation

### ISSUE THREAD

**Issue by pierreburel** [formkit/auto-animate#27]
Great work for this awesome library!

Would be nice to have an option to disable animation programmatically, for example when doing drag'n'drop.

Crude example with react-beautiful-dnd:

```
const [autoAnimateEnabled, setAutoAnimateEnabled] = useState(true);
const [autoAnimateRef] = useAutoAnimate({
  enabled: autoAnimateEnabled,
});

return (
  <DragDropContext 
    onDragStart={() => setAutoAnimateEnabled(false)} 
    onDragEnd={() => setAutoAnimateEnabled(true)}
  >
    <Droppable droppableId="droppable">
      {(provided) => (
        <ul {...provided.droppableProps} ref={mergeRefs([provided.innerRef, autoAnimateRef])}>
```

I guess with the Vue directive it should look like this : `<ul v-auto-animate="{ enabled: autoAnimateEnabled }">`.

**Comment by mtsknn** [comment]
Bikeshedding:

Would a `disabled` option be better since animations are enabled by default?

- "Set `enabled: false` to disable the animations." → Uses the words "enabled" and "disabled."
- "Set `disabled: true` to disable the animations." → Uses the word "disable(d)" twice. This feels more "natural" since the option is about disabling the animations. (It's more about disabling the animations than enabling the animations since animations are enabled by default.)

Eh, I'm not actually sure which one would be better.

**Comment by pierreburel** [comment]
You’re right, `disabled` option would be way better 👍

**Comment by justin-schroeder** [comment]
The plan has been to return a second value in the tuple. similar to `setState`, but it would be something like `setAnimations`

```jsx
const [animateRed, setAnimation] = useAutoAnimate()
// Enabled by default
return (
  <SomeComplexInteraction
    onComplexEvent="() => setAnimation(false)"
    onOtherComplexEvent="() => setAnimation(true)"
  >
    { /*...*/ }
  </SomeComplexInteraction>
)
```
