### ISSUE TITLE
Feature Request: Hidden Elements

### ISSUE THREAD

**Issue by AlexejLiebenthal** [formkit/auto-animate#39]
Is it possible that `add`/`remove` not only reacts if the element is actually added/removed from the DOM, but also when the `hidden` state changes?

If you guide me in the right direction, I also would be happy to contribute 🙂

**Comment by justin-schroeder** [comment]
No sorry — this is not on the roadmap. There are lots of great ways to do this already with CSS transitions.

**Comment by thanhnguyen2187** [comment]
Hi @justin-schroeder.

Can you tell me more about those CSS transitions?

My story is I wanted to create a custom-arrangable cards which are draggable with Svelte (`use:autoAnimate`). The library worked as expected until I hit an issue where `dragend` is not fired if I drag the card out of the zone completely or hit Escape. I dug into it a bit, and it turns out that on `dragstart`, I removed the card's node out of DOM, and that removal caused the issue. I could modify my logic to using `display: none` to make `dragend` firing works, but that renders `use:autoAnimate` useless since the DOM is not changed.

Many thanks!
